name: ngrok
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: ngrok secure introspectable tunnels to localhost.
description: |
  ngrok secure introspectable tunnels to localhost webhook development tool and debugging tool.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

parts:
  ngrok:
    plugin: dump
    source:
      - on amd64: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      - on i386: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip
    override-prime: |
      snapcraftctl prime
      echo $(./ngrok --version | cut -d " " -f 3) > $SNAPCRAFT_STAGE/version

apps:
  ngrok:
    command: ngrok
    plugs: [network, network-bind, home]

plugs:
  ngrok-config-dir:
    interface: personal-files
    write:
    - $HOME/.ngrok2
